name: Deploy Firebase Functions Manually

on:
  workflow_dispatch:

jobs:
  deploy_functions:
    name: Deploy Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create firebaseConfig.json for Project ID extraction
        run: echo '${{ secrets.FIREBASE_CONFIG_JSON }}' > src/firebaseConfig.json

      - name: Install jq and Extract Project ID
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          PROJECT_ID=$(jq -r '.projectId' src/firebaseConfig.json)
          if [ -z "$PROJECT_ID" ] || [ "$PROJECT_ID" == "null" ]; then
            echo "Error: projectId could not be extracted from FIREBASE_CONFIG_JSON."
            exit 1
          fi
          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_AGENT_WEB_UI }}

      - name: Configure Google ADC  
        run: |  
          mkdir -p ~/.config/gcloud  
          cp "${{ steps.auth.outputs.credentials_file_path }}" ~/.config/gcloud/application_default_credentials.json 

      - name: Prepare Python Env
        working-directory: ./functions
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add environment secrets to .env  
        env:  
          SECRETS: "OPENAI_API_KEY,GEMINI_API_KEY,ANTHROPIC_API_KEY,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION_NAME,LLAMA_API_KEY,MISTRAL_API_KEY,WATSONX_APIKEY,WATSONX_TOKEN,WATSONX_URL,WATSONX_PROJECT_ID,DEEPSEEK_API_KEY,DEEPINFRA_API_KEY,REPLICATE_API_KEY,TOGETHER_AI_API_KEY,AZURE_API_KEY,AZURE_API_BASE,AZURE_API_VERSION,GITH_TOKEN" # Comma separated list of your secrets
        working-directory: ./functions
        run: |  
          touch .env
          for SECRET in $(echo $SECRETS | sed "s/,/ /g")  
          do  
            # Check if the secret is GITH_TOKEN and rename it to GITHUB_TOKEN  
            if [ "$SECRET" = "GITH_TOKEN" ]; then  
              OUTPUT_SECRET_NAME="GITHUB_TOKEN"  
            else  
              OUTPUT_SECRET_NAME="$SECRET"  
            fi  
            # Append the secret to the .env file  
            echo "${OUTPUT_SECRET_NAME}=${!SECRET}" >> .env
          done

      - name: Deploy Firebase Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          GOOGLE_CLOUD_PROJECT: ${{ env.PROJECT_ID }}
          GCLOUD_PROJECT: ${{ env.PROJECT_ID }}
          PROJECT_ID: agent-web-ui
        working-directory: ./
        run: |  
          echo "--- Environment for Firebase Deploy ---"  
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"  
          echo "GOOGLE_CLOUD_PROJECT: $GOOGLE_CLOUD_PROJECT"  
          echo "GCLOUD_PROJECT: $GCLOUD_PROJECT"  
          echo "Current directory: $(pwd)"  
          ls -la # Show files in current directory, check for firebase.json  
          echo "---------------------------------------"  
            
          echo "Deploying Functions to project: $GOOGLE_CLOUD_PROJECT"  
          firebase deploy --only functions --project "$GOOGLE_CLOUD_PROJECT"

      - name: Clean up config file
        if: always()
        run: rm -f src/firebaseConfig.json
